# Generated by Django 3.1.7 on 2021-05-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarSampel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_survei', models.CharField(max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('wilayah', models.CharField(max_length=200, null=True)),
                ('penanggung_jawab', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(choices=[('Daftar Sampel Blok Sensus', 'Daftar Sampel Blok Sensus'), ('Daftar Sampel Rumah Tangga/Non, Usaha/Non', 'Daftar Sampel Rumah Tangga/Non, Usaha/Non'), ('Laporan Kegiatan', 'Laporan Kegiatan')], max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='static/file_upload/Daftar_Sampel/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian_dipa', models.CharField(max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('file_pok', models.FileField(null=True, upload_to='static/file_upload/Dipa/POK')),
                ('file_adk', models.FileField(null=True, upload_to='static/file_upload/Dipa/ADK')),
                ('file_dipa', models.FileField(null=True, upload_to='static/file_upload/Dipa/DIPA')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_spm', models.CharField(max_length=200, null=True)),
                ('jenis_spm', models.CharField(max_length=200, null=True)),
                ('tanggal_spm', models.DateField(null=True)),
                ('nomor_sp2d', models.CharField(max_length=200, null=True)),
                ('tanggal_sp2', models.DateField(null=True)),
                ('jumlah_potongan', models.IntegerField(null=True)),
                ('jumlah_bersih', models.IntegerField(null=True)),
                ('file_spm', models.FileField(null=True, upload_to='static/file_upload/SPM/SPM/')),
                ('file_sp2d', models.FileField(null=True, upload_to='static/file_upload/SPM/SP2D/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('perihal', models.CharField(max_length=200, null=True)),
                ('tanggal_surat', models.DateField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='static/file_upload/Surat/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Survei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_survei', models.CharField(max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('penanggung_jawab', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(choices=[('Kuesioner', 'Kuesioner'), ('Berita Acara Respon Rate', 'Berita Acara Respon Rate'), ('Laporan Kegiatan', 'Laporan Kegiatan')], max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='static/file_upload/Survei/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('tanggal_surat', models.DateField(null=True)),
                ('jumlah_tup', models.IntegerField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='static/file_upload/Surat/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Umum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(choices=[('Backup Aplikasi SAS', 'Backup Aplikasi SAS'), ('Backup Aplikasi Persediaan', 'Backup Aplikasi Persediaan'), ('Backup Aplikasi SIMAK BMN', 'Backup Aplikasi SIMAK BMN'), ('Backup Aplikasi GPP', 'Backup Aplikasi GPP'), ('Backup Aplikasi SAIBA', 'Backup Aplikasi SAIBA'), ('Laporan Kondisi Barang', 'Laporan Kondisi Barang'), ('Laporan Pengadaan Barang dan Jasa', 'Laporan Pengadaan Barang dan Jasa'), ('LPJ Perbendaharaan Pengeluaran', 'LPJ Perbendaharaan Pengeluaran'), ('Buku Kas Umum', 'Buku Kas Umum'), ('Buku Pembantu Pajak', 'Buku Pembantu Pajak'), ('Buku Besar Kas', 'Buku Besar Kas'), ('Berita Acara Rekonsiliasi e-Rekon', 'Berita Acara Rekonsiliasi e-Rekon'), ('Form Rencana Aksi', 'Form Rencana Aksi')], max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('upload', models.FileField(null=True, upload_to='static/file_upload/Umum1/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
