# Generated by Django 3.1.7 on 2021-05-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0002_auto_20210508_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarsampel',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='umum',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
