# Generated by Django 3.1.7 on 2021-05-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0003_auto_20210508_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipa',
            name='uraian_dipa',
        ),
        migrations.AddField(
            model_name='dipa',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='umum',
            name='upload',
            field=models.FileField(null=True, upload_to='static/file_upload/Umum/'),
        ),
    ]
