# Generated by Django 3.1.7 on 2021-05-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0004_auto_20210508_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dipa',
            old_name='description',
            new_name='uraian_dipa',
        ),
    ]
