# Generated by Django 3.1.7 on 2021-05-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0006_auto_20210508_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spm',
            old_name='tanggal_sp2',
            new_name='tanggal_sp2d',
        ),
    ]
