# Generated by Django 3.2.4 on 2021-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0010_alter_tup_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='kategori',
            field=models.CharField(choices=[('Kuesioner', 'Kuesioner'), ('Berita Acara Respon Rate', 'Berita Acara Respon Rate')], max_length=200, null=True),
        ),
    ]
