# Generated by Django 3.2.4 on 2021-06-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0011_alter_survei_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umum',
            name='nama',
        ),
    ]
