# Generated by Django 3.2.4 on 2021-06-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0012_remove_umum_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dipa',
            old_name='periode',
            new_name='tanggal',
        ),
    ]
