# Generated by Django 3.2.4 on 2021-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0013_rename_periode_dipa_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarsampel',
            name='penanggung_jawab',
            field=models.CharField(choices=[('Statistik Sosial', 'Statistik Sosial'), ('Statistik Produksi', 'Statistik Produksi'), ('Statistik Distribusi', 'Statistik Distribusi'), ('Neraca Wilayah dan Analisis Statistik', 'Neraca Wilayah dan Analisis Statistik'), ('Integrasi Pengolahan dan Diseminasi Statistik', 'Integrasi Pengolahan dan Diseminasi Statistik')], max_length=200, null=True),
        ),
    ]
