# Generated by Django 3.2.4 on 2021-06-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arsip', '0014_alter_daftarsampel_penanggung_jawab'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAplikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Backup Aplikasi SAS', 'Backup Aplikasi SAS'), ('Backup Aplikasi Persediaan', 'Backup Aplikasi Persediaan'), ('Backup Aplikasi SIMAK BMN', 'Backup Aplikasi SIMAK BMN'), ('Backup Aplikasi GPP', 'Backup Aplikasi GPP'), ('Backup Aplikasi SAIBA', 'Backup Aplikasi SAIBA'), ('Laporan Kondisi Barang', 'Laporan Kondisi Barang'), ('Laporan Pengadaan Barang dan Jasa', 'Laporan Pengadaan Barang dan Jasa'), ('LPJ Perbendaharaan Pengeluaran', 'LPJ Perbendaharaan Pengeluaran'), ('Buku Kas Umum', 'Buku Kas Umum'), ('Buku Pembantu Pajak', 'Buku Pembantu Pajak'), ('Buku Besar Kas', 'Buku Besar Kas'), ('Berita Acara Rekonsiliasi e-Rekon', 'Berita Acara Rekonsiliasi e-Rekon'), ('Form Rencana Aksi', 'Form Rencana Aksi')], max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='file_upload/BackupAplikasi/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
