# Generated by Django 3.2.4 on 2021-06-10 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arsip', '0016_auto_20210611_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanbmn',
            name='kategori',
            field=models.CharField(choices=[('Laporan Kondisi Barang', 'Laporan Kondisi Barang'), ('Laporan Pengadaan Barang dan Jasa', 'Laporan Pengadaan Barang dan Jasa'), ('LPJ Perbendaharaan Pengeluaran', 'LPJ Perbendaharaan Pengeluaran'), ('Buku Kas Umum', 'Buku Kas Umum'), ('Buku Pembantu Pajak', 'Buku Pembantu Pajak'), ('Buku Besar Kas', 'Buku Besar Kas')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LaporanKinerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Berita Acara Rekonsiliasi e-Rekon', 'Berita Acara Rekonsiliasi e-Rekon'), ('Form Rencana Aksi', 'Form Rencana Aksi')], max_length=200, null=True)),
                ('periode', models.DateField(null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('upload', models.FileField(null=True, upload_to='file_upload/Umum/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
